### ISSUE TITLE
when using firedpy: ERROR: no module called 'bs4'

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#10]
Looks like the environment.yaml file might need to be updated?

Here's the Error output:
(base) root@cbd2f1f21fcc:/home/firedpy# firedpy
Traceback (most recent call last):
  File "/opt/conda/bin/firedpy", line 11, in <module>
    load_entry_point('firedpy==0.0.1', 'console_scripts', 'firedpy')()
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/conda/lib/python3.7/site-packages/firedpy-0.0.1-py3.7.egg/firedpy/__main__.py", line 3, in <module>
  File "/opt/conda/lib/python3.7/site-packages/firedpy-0.0.1-py3.7.egg/firedpy/functions.py", line 2, in <module>
ModuleNotFoundError: No module named 'bs4'

**Comment by admahood** [comment]
@maxwellcook looks like another minor bug came up

**Comment by admahood** [comment]
@maxwellCcook

**Comment by maxwellCcook** [comment]
This is interesting. No idea what bs4 is and I did not use a module by that name (did not change any modules). Looking into it now and will report back soon.

**Comment by maxwellCcook** [comment]
its the beautifulsoup4 module ... might be a name issue in the environment.yaml

**Comment by maxwellCcook** [comment]
So my commit did not actually ever make it here. The changes I made are not reflected in the current repo. Also, I could not recreate this error initially.
