### ISSUE TITLE
path error that occurrs only when world ecoregions are selected

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#57]
file:///home/a/Desktop/Screenshot%20from%202021-08-20%2016-11-12.png

**Comment by admahood** [comment]
Traceback (most recent call last):
  File "/opt/conda/envs/firedpy/bin/firedpy", line 33, in <module>
    sys.exit(load_entry_point('firedpy==0.0.2', 'console_scripts', 'firedpy')())
  File "/opt/conda/envs/firedpy/lib/python3.7/site-packages/firedpy-0.0.2-py3.7.egg/firedpy/__main__.py", line 469, in main
  File "/opt/conda/envs/firedpy/lib/python3.7/site-packages/firedpy-0.0.2-py3.7.egg/firedpy/functions.py", line 1652, in buildFireAttributes
  File "/opt/conda/envs/firedpy/lib/python3.7/site-packages/firedpy-0.0.2-py3.7.egg/firedpy/functions.py", line 1632, in buildPoints
  File "/opt/conda/envs/firedpy/lib/python3.7/site-packages/geopandas/io/file.py", line 160, in _read_file
    with reader(path_or_bytes, **kwargs) as features:
  File "/opt/conda/envs/firedpy/lib/python3.7/site-packages/fiona/env.py", line 398, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/envs/firedpy/lib/python3.7/site-packages/fiona/__init__.py", line 254, in open
    layer=layer, enabled_drivers=enabled_drivers, **kwargs)
  File "/opt/conda/envs/firedpy/lib/python3.7/site-packages/fiona/collection.py", line 154, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 484, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 90, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: ref/individual_countries/canada.gpkg: No such file or directory

**Comment by admahood** [comment]
screenshot does not appear to be pasting in right
